const ServicesData = [
  {
    title: "Frontend Development",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/03a9f6fc484719e6ce9349f4a57aae9cb75bdcc9-600x600.svg",
    tags: [
      "HTML5",
      "CSS3",
      "SaaS",
      "JavaScript",
      "ReactJS",
      "ReactNative",
      "Nextjs",
      "Material-UI",
      "Bootstrap",
      "VueJS",
      "AngularJS",
      "Figma",
    ],
  },
  {
    title: "Backend Development",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/1ca784a9bf93dc47756fdb2cb8a33aeeca20fb75-128x128.svg",
    tags: [
      "Python",
      "Django",
      "Flask",
      "Django REST Framework",
      "NodeJS",
      "ExpressJS",
      "CorePHP",
      "Laravel",
      "CodeIgnitor",
      "C#",
      ".NET",
      "ASP.NET",
      "Scrapy",
      "Selenium",
      "BeautifulSoup",
      "Bash Scripting",
      "Elastic Search",
      "Celery",
      "RabbitMQ",
      "MailChimp",
      "ETL Process",
    ],
  },
  {
    title: "DataBase & DevOps",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/f407fcbd4c04d8affdf00209abe608ec708a1388-512x512.svg",
    tags: [
      "MySQL",
      "PostgreSQL",
      "SQLite",
      "Oracle",
      "MongoDB",
      "DynamoDB",
      "Google Cloud SQL",
      "Azure SQL Database",
      "EC2",
      "Elastic Beanstalk",
      "Lambda",
      "Fargate",
      "CI/CD Pipeline",
      "Cognito",
      "Amplify",
      "SNS",
      "SQS",
      "API Gateway",
      "Route 53",
      "S3",
      "Microsoft Azure",
      "Heroku",
      "Google Cloud Platform",
      "Docker",
      "Jenkins",
    ],
  },

  {
    title: "Data Science",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/a13e377822ec30af9894808787bcacfae6d3d02d-128x128.png",
    tags: [
      "Data Analysis",
      "Data Migration",
      "Data Cleansing",
      "Transformation",
      "Integration",
      "Data Import",
      "Data Export",
      "Spark",
      "Hadoop",
      "Kafka",
      "Cassandra",
      "Hdfs",
      "Zookeeper",
    ],
  },
];
export default ServicesData;
